# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Developers Market
email: xoeseko@gmail.com
tagline: A Decentralized Market to Incentivize Sharing Knowledge and Expertise for achieving the UN SDGs
description: >- # this means to ignore newlines until "baseurl:"
  This website is developped by Sofia Delijaj and Xoeseko Nyomi as part of their Open Science project.
  The aim is to review the sdg-market to make it production ready. Apply checks and balances
  from the goals set in the whitepaper vs the actual implementation. Add data visualisations
  just like there could be on an actual financial platform and document the whole process.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
# github_username:  Xoeseko and Sofia-Pika
# github: [metadata]
hero_img: posts/samuel-zeller-358003-unsplash_lg.jpg
navigation:
  - {name: 'Home', link: '/'}
  - {name: 'Whitepaper', link: '/whitepaper'}
  # - {name: 'Token chart', link: '/data visualisations/dynamicVisu'}
  - {name: 'Checks and balances', link: '/checks_and_balances/'}
  # - {name: 'Contributions', link: '/data visualisations/contributions'}
  - {name: 'About', link: '/about/'}
  # - {name: 'Test dyn viz', link: '/data visualisations/test'}

# Build settings
markdown: kramdown
##theme: "minimal-mistakes-jekyll"
remote_theme: "janczizikow/sleek"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate

defaults:
  #_posts
   -
     scope:
      path: ""
      type: posts
     values:
      # layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

repository: developers-market/developers-market
# minimal_mistakes_skin: "dark" # "default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#theme: jekyll-theme-minimal
people:
- name: Sofia Delijaj
  pic: Delijaj
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Thomas Mayar
  pic: thomas
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Xoeseko Nyomi
  pic: id_xoeseko
  position: Lead Developer
  social:
    - title: gitHub
      url: https://github.com/Xoeseko/
    - title: facebook
      url: https://www.facebook.com/xnyomi
    - title: stack-overflow
      url: https://stackoverflow.com/users/9117755/xoeseko-yao-nyomi
future: false
